#!/usr/bin/env python3
"""Deterministic builder for llms.txt and llms-full.txt.

Reads the documentation corpus under docs/ (order and descriptions derived
from docs/index.md) and writes two generated artifacts at the repository root:

  llms.txt       compact entry point: orientation + sectioned links
  llms-full.txt  consolidated corpus: every page verbatim after a separator

Standard library only. No timestamps, no absolute paths, no randomness:
the same docs/ tree always yields byte-identical outputs (UTF-8, LF).

Usage:
  python scripts/build_llms.py          build/refresh both artifacts
  python scripts/build_llms.py --check  verify artifacts match; no writes
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX = DOCS / "index.md"
OUT_TXT = ROOT / "llms.txt"
OUT_FULL = ROOT / "llms-full.txt"

LINK_RE = re.compile(r"^-\s+\[([^\]]+)\]\(([^)]+)\)\s*(?:—\s*(.*))?\s*$")
HEADING_RE = re.compile(r"^##\s+(.*)\s*$")
SEP = "=" * 74

HEADER_TXT = """\
# lsp-llms

> Structured English documentation for LSP — Linguagem Senior de Programação
> (Senior Programming Language), transformed from community documentation for
> LLM and coding-agent consumption.

This file is generated by `scripts/build_llms.py`. Do not edit manually.

Orientation:

- The pages below are the source of truth for documented LSP behavior.
- Respect the evidence labels used across the corpus (`Source-faithful`,
  `Excerpt`, `Demonstrated`, `Observed-only`, `Project guidance`,
  `Conflict / uncertainty`); see the Evidence vocabulary in `docs/index.md`.
- Conflicts are preserved explicitly, never silently resolved; follow the
  safest documented pattern and verify against official Senior documentation.
- Senior Sistemas is the authoritative source for official product behavior.
"""

HEADER_FULL = """\
# lsp-llms — consolidated reference (generated)

> Generated deterministically from the Markdown corpus under `docs/` by
> `scripts/build_llms.py`. Do not edit manually; edit the sources under
> `docs/` and regenerate.
"""


class CorpusError(Exception):
    """Malformed corpus or navigation; build must fail, not guess."""


def read_utf8(path):
    try:
        raw = path.read_bytes().decode("utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise CorpusError(f"cannot read UTF-8 file: {path}: {exc}")
    return "\n".join(raw.splitlines()) + "\n"


def parse_index(text):
    """Parse docs/index.md into [(section, [entries])].

    Linked entries: (title, posix_relpath, description_or_None).
    Plain bullets (e.g. not-yet-transformed domains): (text, None, None).
    Only H2 sections and '-' bullets are considered; everything else ignored.
    """
    sections = []
    current = None
    for raw_line in text.splitlines():
        line = raw_line.strip()
        heading = HEADING_RE.match(line)
        if heading:
            current = (heading.group(1), [])
            sections.append(current)
            continue
        if current is None or not line.startswith("- "):
            continue
        link = LINK_RE.match(line)
        if link:
            title, rel, desc = link.group(1), link.group(2), link.group(3)
            current[1].append({"title": title, "link": rel,
                               "desc": desc.strip() if desc else None,
                               "raw": line})
        else:
            current[1].append({"title": None, "link": None,
                               "desc": None, "raw": line[2:].strip()})
    if not sections:
        raise CorpusError("docs/index.md contains no '## ' sections")
    return sections


def resolve_doc(rel):
    """Resolve an index link to a docs/ file; fail on escape/missing/non-md."""
    posix = rel.replace("\\", "/").strip()
    if not posix or posix.startswith(("#", "http://", "https://", "mailto:")):
        raise CorpusError(f"index link is not a docs/ page: {rel!r}")
    candidate = (DOCS / posix)
    try:
        resolved = candidate.resolve()
    except OSError as exc:
        raise CorpusError(f"cannot resolve index link {rel!r}: {exc}")
    try:
        resolved.relative_to(DOCS.resolve())
    except ValueError:
        raise CorpusError(f"index link escapes docs/: {rel!r}")
    if resolved.suffix.lower() != ".md":
        raise CorpusError(f"index link is not a Markdown file: {rel!r}")
    if not resolved.is_file():
        raise CorpusError(f"indexed file does not exist: {rel!r}")
    return resolved.relative_to(DOCS.resolve()).as_posix()


def ordered_corpus():
    """Return (ordered_rel_paths, warnings).

    docs/index.md first, then linked pages in index order, then any
    unreferenced docs/**/*.md in lexicographic order (with a warning).
    Duplicates across the whole list are an error.
    """
    index_text = read_utf8(INDEX)
    sections = parse_index(index_text)
    ordered = ["index.md"]
    seen = {"index.md"}
    for _, entries in sections:
        for entry in entries:
            if entry["link"] is None:
                continue
            rel = resolve_doc(entry["link"])
            if rel in seen:
                raise CorpusError(f"duplicate indexed document: {rel!r}")
            seen.add(rel)
            ordered.append(rel)
    warnings = []
    unreferenced = sorted(
        p.relative_to(DOCS).as_posix()
        for p in DOCS.rglob("*.md")
        if p.relative_to(DOCS).as_posix() not in seen
    )
    for rel in unreferenced:
        warnings.append(f"WARNING: docs page not referenced by index: {rel}")
        ordered.append(rel)
    return ordered, warnings, sections


def build_llms_txt(ordered, sections):
    """Compact entry point; descriptions come from docs/index.md."""
    lines = [HEADER_TXT.rstrip("\n"), ""]
    for title, entries in sections:
        lowered = title.lower()
        if title == "Source":
            continue
        if lowered.startswith("not yet"):
            lines.append("## Not yet documented")
            lines.append("")
            for entry in entries:
                if entry["link"] is None:
                    lines.append(f"- {entry['raw']}")
            lines.append("")
            continue
        if lowered.startswith("evidence"):
            continue
        linked = [e for e in entries if e["link"] is not None]
        if not linked:
            continue
        lines.append(f"## {title}")
        lines.append("")
        for entry in linked:
            rel = resolve_doc(entry["link"])
            href = f"docs/{rel}"
            if entry["desc"]:
                lines.append(f"- [{entry['title']}]({href}): {entry['desc']}")
            else:
                lines.append(f"- [{entry['title']}]({href})")
        lines.append("")
    lines.append("## Limitations and conflicts")
    lines.append("")
    lim_desc = None
    for _, entries in sections:
        for entry in entries:
            if entry["link"] is not None and resolve_doc(entry["link"]) == "guides/limitations.md":
                lim_desc = entry["desc"]
    if lim_desc:
        lines.append(f"- [Critical limitations and common pitfalls](docs/guides/limitations.md): {lim_desc}")
    else:
        raise CorpusError("guides/limitations.md not indexed; cannot build limitations section")
    lines.append("- Every domain page records its own conflicts and uncertainties explicitly; "
                 "follow the safest documented pattern.")
    lines.append("")
    lines.append("## Full reference")
    lines.append("")
    lines.append("- [llms-full.txt](llms-full.txt): the complete consolidated corpus "
                 "(every page verbatim, in index order).")
    lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def build_llms_full(ordered):
    parts = [HEADER_FULL.rstrip("\n"), ""]
    for rel in ordered:
        content = read_utf8(DOCS / rel).rstrip("\n")
        parts.append(SEP)
        parts.append(f"SOURCE: docs/{rel}")
        parts.append(SEP)
        parts.append("")
        parts.append(content)
        parts.append("")
    return "\n".join(parts).rstrip("\n") + "\n"


def build_all():
    ordered, warnings, sections = ordered_corpus()
    return {"llms.txt": build_llms_txt(ordered, sections),
            "llms-full.txt": build_llms_full(ordered),
            "ordered": ordered,
            "warnings": warnings}


def cmd_build():
    try:
        result = build_all()
    except CorpusError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    for warning in result["warnings"]:
        print(warning, file=sys.stderr)
    OUT_TXT.write_text(result["llms.txt"], encoding="utf-8", newline="\n")
    OUT_FULL.write_text(result["llms-full.txt"], encoding="utf-8", newline="\n")
    print(f"wrote {OUT_TXT} ({len(result['llms.txt'].encode('utf-8'))} bytes, "
          f"{len(result['ordered'])} documents in llms-full.txt)")
    return 0


def cmd_check():
    try:
        result = build_all()
    except CorpusError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    for warning in result["warnings"]:
        print(warning, file=sys.stderr)
    expected = (("llms.txt", OUT_TXT, result["llms.txt"]),
                ("llms-full.txt", OUT_FULL, result["llms-full.txt"]))
    failed = False
    for name, path, want in expected:
        if not path.is_file():
            print(f"DRIFT: {name} is missing", file=sys.stderr)
            failed = True
            continue
        try:
            got = path.read_bytes().decode("utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            print(f"DRIFT: {name} unreadable: {exc}", file=sys.stderr)
            failed = True
            continue
        if got != want:
            print(f"DRIFT: {name} differs from generated content", file=sys.stderr)
            failed = True
    if failed:
        return 1
    print(f"OK: llms.txt and llms-full.txt match generated content "
          f"({len(result['ordered'])} documents)")
    return 0


def main(argv):
    if len(argv) == 2 and argv[1] == "--check":
        return cmd_check()
    if len(argv) == 1:
        return cmd_build()
    print(f"usage: {argv[0]} [--check]", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
